<form method="post" action="<?php echo App::config('url') ?>Index/newPost">

    <div class="form-group">
        <input id="content" name="content" placeholder="Unesi novi post">
    </div>
    <button type="submit" class="btn btn-primary">Dodaj post</button>

</form>

<?php foreach ($posts as $post): ?>
    <p>
        <?php echo $post->getDateCreated()->format('d.m.Y. H:i') . '<br>' ?>
        <a href="<?php echo App::config('url')?>Index/view/<?= $post->getId() ?> ">
            <?php echo htmlspecialchars($post->getContent()); ?>
        </a>
    </p>
<?php endforeach; ?>