<?php echo $post->getDateCreated()->format('d.m.Y. H:i') . '<br>' ?>

<p><?= htmlspecialchars($post->getContent())?></p>

<form action="<?php echo App::config('url') ?>Index/uploadImage/<?= $post->getId() ?>" method="post" enctype="multipart/form-data">
    <div>
        <input type="file" name="fileToUpload" id="fileToUpload"> <br>
        <input type="submit" value="Upload Image" name="submit"> <br>
    </div>
</form>